### ISSUE TITLE
[Quest] tools/nav.lua:26: 'union 96' has no member named 'save'

### ISSUE THREAD

**Issue by Ulydev** [sophiabaldonado/layout#1]
Hello!
On Oculus Quest, layout crashes immediately with the following error message:
`tools/nav.lua:26: 'union 96' has no member named 'save'`
I'm not familiar enough with the API yet to make a guess, but could it be due to the changes between 0.12 and 0.13?
Thanks!

**Comment by Ulydev** [comment]
Removing the call to :save() gets past the error screen, but makes lovr crash (without any error message) - this might be Quest-specific, though.
Does this need any preliminary setup (scene, assets) before running it to work? Or do you have a sample project available to try?

EDIT: running it on macOS, with the call to :save(), doesn't show an error but makes lovr crash the same way (segmentation fault)

**Comment by shakesoda** [comment]
@Ulydev if you set t.math.ffi = false in lovr.conf does this still happen?

**Comment by Ulydev** [comment]
@shakesoda thank you for the help, I can't seem to disable math.ffi specifically though.
`t.math.ffi = false` throws "math is nil", and `t.modules.math` is a boolean, not a table :(

**Comment by shakesoda** [comment]
`t.math = { ffi = false }` ?

if this doesn't work you might need a newer lovr build

**Comment by Ulydev** [comment]
Hm, you're right. I've tried that too, but segmentation fault still happens. I might have a broken build somehow.

**Comment by bjornbytes** [comment]
Things have since been updated to the latest version
